### ISSUE TITLE
Fix permissions in install script

### ISSUE THREAD

**Issue by martinfiers** [ptone/jiffylab#18]
Currently, the linux-setup.sh does not execute properly as a normal user. There's a mix of sudo and non-sudo commands, which confuses me on how to install jiffylab.

Probably, the problem is fixed when adding 'sudo' in front of some of the commands that usually require elevated permissions, such as the stop/start/useradd, and writing towards /etc/init/jiffylabweb.conf and /etc/init/dockerd.conf. 

I'm not sure about the actual purpose of this install script (should it be run as root user, i.e., after removing all sudo's from the install script, or should it be run as a normal user).

I can make a pull request if I'm sure about the strategy of this file (and after testing on my PC).

Regards,
Martin

**Comment by davclark** [comment]
Preston is aware of this issue, and there have been a number of us working on a unified, functional approach to doing jiffylab setup. So, in the off chance that he doesn't respond, know that it is being worked on, but there hasn't been much impetus to push to a public repo (this work is interfacing with a bunch of other requirements for setting up things in a UC Berkeley campus-specific way).

I think the easiest thing for now is to just run as root. It's a very specific-use VM, so there's less reason to be cautious. (If there is, please correct me).

**Comment by ptone** [comment]
@martinfiers thanks for submitting this

The main issue is ambiguity among vagrant providers about whether the default user is root. For some cloud provider vagrant plugins, the remain with the default user of the cloud image, while others create a vagrant user, who is not root, but is in the sudoers list.  So really there should not be sudo lines in the script, the whole thing should be run as root - either as root directly or via sudo.

**Comment by martinfiers** [comment]
Thanks for the feedback. That sounds good to me: to remove the sudo lines. I don't want to break anything in your setup, so I guess it's better if you first test it.

**Comment by ptone** [comment]
problem is that some of the providers have a non-root vagrant user, so sudo is required.

I've at least fixed it up to be consistent for now, will investigate using an inline shell script in the vagrant file at another time.
